# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1340, 539)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 1271, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.label_filters_input = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_input.setGeometry(QtCore.QRect(180, 30, 331, 231))
        self.label_filters_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_input.setObjectName("label_filters_input")
        self.label_filters_output = QtWidgets.QLabel(self.tab_filters)
        self.label_filters_output.setGeometry(QtCore.QRect(520, 30, 331, 231))
        self.label_filters_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_filters_output.setTextFormat(QtCore.Qt.PlainText)
        self.label_filters_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_filters_output.setObjectName("label_filters_output")
        self.pushButton_filters_load = QtWidgets.QPushButton(self.tab_filters)
        self.pushButton_filters_load.setGeometry(QtCore.QRect(20, 30, 121, 81))
        self.pushButton_filters_load.setObjectName("pushButton_filters_load")
        self.label = QtWidgets.QLabel(self.tab_filters)
        self.label.setGeometry(QtCore.QRect(30, 140, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_filters)
        self.label_2.setGeometry(QtCore.QRect(30, 170, 71, 21))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_filters)
        self.groupBox.setGeometry(QtCore.QRect(30, 280, 751, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(430, 20, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 30, 311, 71))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 30, 171, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(590, 80, 151, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(430, 80, 91, 21))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_filters, "")
        self.tab_histograms = QtWidgets.QWidget()
        self.tab_histograms.setObjectName("tab_histograms")
        self.label_histograms_houtput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_houtput.setGeometry(QtCore.QRect(640, 200, 261, 191))
        self.label_histograms_houtput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_houtput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_houtput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_houtput.setObjectName("label_histograms_houtput")
        self.label_histograms_input = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_input.setGeometry(QtCore.QRect(390, 20, 241, 171))
        self.label_histograms_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input.setObjectName("label_histograms_input")
        self.label_histograms_output = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_output.setGeometry(QtCore.QRect(640, 20, 261, 171))
        self.label_histograms_output.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output.setObjectName("label_histograms_output")
        self.label_10 = QtWidgets.QLabel(self.tab_histograms)
        self.label_10.setGeometry(QtCore.QRect(270, 120, 71, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_histograms)
        self.label_11.setGeometry(QtCore.QRect(270, 90, 71, 21))
        self.label_11.setObjectName("label_11")
        self.label_histograms_hinput = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_hinput.setGeometry(QtCore.QRect(390, 200, 241, 191))
        self.label_histograms_hinput.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput.setObjectName("label_histograms_hinput")
        self.label_histograms_hinput_3 = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_hinput_3.setGeometry(QtCore.QRect(10, 20, 241, 191))
        self.label_histograms_hinput_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_3.setObjectName("label_histograms_hinput_3")
        self.label_6 = QtWidgets.QLabel(self.tab_histograms)
        self.label_6.setGeometry(QtCore.QRect(530, 0, 271, 16))
        self.label_6.setObjectName("label_6")
        self.label_histograms_hinput_4 = QtWidgets.QLabel(self.tab_histograms)
        self.label_histograms_hinput_4.setGeometry(QtCore.QRect(10, 220, 241, 191))
        self.label_histograms_hinput_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_4.setObjectName("label_histograms_hinput_4")
        self.pushButton_histograms_load = QtWidgets.QPushButton(self.tab_histograms)
        self.pushButton_histograms_load.setGeometry(QtCore.QRect(270, 180, 91, 31))
        self.pushButton_histograms_load.setObjectName("pushButton_histograms_load")
        self.label_7 = QtWidgets.QLabel(self.tab_histograms)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 271, 16))
        self.label_7.setObjectName("label_7")
        self.coloredhistogram = QtWidgets.QPushButton(self.tab_histograms)
        self.coloredhistogram.setGeometry(QtCore.QRect(70, 420, 111, 31))
        self.coloredhistogram.setObjectName("coloredhistogram")
        self.equalization = QtWidgets.QPushButton(self.tab_histograms)
        self.equalization.setGeometry(QtCore.QRect(574, 410, 121, 31))
        self.equalization.setObjectName("equalization")
        self.tabWidget.addTab(self.tab_histograms, "")
        self.tab_hybrid = QtWidgets.QWidget()
        self.tab_hybrid.setObjectName("tab_hybrid")
        self.label_histograms_input_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_input_2.setGeometry(QtCore.QRect(180, 20, 241, 171))
        self.label_histograms_input_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_input_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_input_2.setObjectName("label_histograms_input_2")
        self.label_histograms_hinput_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_hinput_2.setGeometry(QtCore.QRect(180, 200, 241, 191))
        self.label_histograms_hinput_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_hinput_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_histograms_hinput_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_hinput_2.setObjectName("label_histograms_hinput_2")
        self.label_histograms_output_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_histograms_output_2.setGeometry(QtCore.QRect(430, 20, 431, 371))
        self.label_histograms_output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_histograms_output_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_histograms_output_2.setObjectName("label_histograms_output_2")
        self.label_12 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 71, 21))
        self.label_12.setObjectName("label_12")
        self.pushButton_histograms_load_2 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_2.setGeometry(QtCore.QRect(20, 20, 121, 81))
        self.pushButton_histograms_load_2.setObjectName("pushButton_histograms_load_2")
        self.label_13 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_13.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_14.setGeometry(QtCore.QRect(30, 310, 71, 21))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_hybrid)
        self.label_15.setGeometry(QtCore.QRect(30, 290, 71, 21))
        self.label_15.setObjectName("label_15")
        self.pushButton_histograms_load_3 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_3.setGeometry(QtCore.QRect(20, 200, 121, 81))
        self.pushButton_histograms_load_3.setObjectName("pushButton_histograms_load_3")
        self.pushButton_histograms_load_4 = QtWidgets.QPushButton(self.tab_hybrid)
        self.pushButton_histograms_load_4.setGeometry(QtCore.QRect(20, 350, 121, 41))
        self.pushButton_histograms_load_4.setObjectName("pushButton_histograms_load_4")
        self.tabWidget.addTab(self.tab_hybrid, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.output_img = QtWidgets.QLabel(self.tab_3)
        self.output_img.setGeometry(QtCore.QRect(470, 20, 321, 241))
        self.output_img.setFrameShape(QtWidgets.QFrame.Box)
        self.output_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.output_img.setObjectName("output_img")
        self.Hough_load = QtWidgets.QPushButton(self.tab_3)
        self.Hough_load.setGeometry(QtCore.QRect(10, 20, 121, 81))
        self.Hough_load.setObjectName("Hough_load")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(20, 120, 71, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(20, 150, 71, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(20, 310, 91, 21))
        self.label_29.setObjectName("label_29")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_7.setGeometry(QtCore.QRect(80, 330, 171, 20))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.Hough_load_2 = QtWidgets.QPushButton(self.tab_3)
        self.Hough_load_2.setGeometry(QtCore.QRect(290, 360, 161, 41))
        self.Hough_load_2.setObjectName("Hough_load_2")
        self.Input_img_2 = QtWidgets.QLabel(self.tab_3)
        self.Input_img_2.setGeometry(QtCore.QRect(140, 20, 321, 241))
        self.Input_img_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_img_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Input_img_2.setObjectName("Input_img_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Input_img_3 = QtWidgets.QLabel(self.tab_4)
        self.Input_img_3.setGeometry(QtCore.QRect(150, 20, 321, 241))
        self.Input_img_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_img_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Input_img_3.setObjectName("Input_img_3")
        self.output_img_2 = QtWidgets.QLabel(self.tab_4)
        self.output_img_2.setGeometry(QtCore.QRect(490, 20, 321, 241))
        self.output_img_2.setFrameShape(QtWidgets.QFrame.Box)
        self.output_img_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.output_img_2.setObjectName("output_img_2")
        self.Hough_load_3 = QtWidgets.QPushButton(self.tab_4)
        self.Hough_load_3.setGeometry(QtCore.QRect(10, 30, 121, 81))
        self.Hough_load_3.setObjectName("Hough_load_3")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(10, 180, 71, 21))
        self.label_31.setObjectName("label_31")
        self.Hough_load_4 = QtWidgets.QPushButton(self.tab_4)
        self.Hough_load_4.setGeometry(QtCore.QRect(20, 290, 111, 41))
        self.Hough_load_4.setObjectName("Hough_load_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(80, 370, 311, 71))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label_39.setObjectName("label_39")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit_4.setGeometry(QtCore.QRect(160, 30, 131, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(470, 370, 311, 71))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_40 = QtWidgets.QLabel(self.groupBox_8)
        self.label_40.setGeometry(QtCore.QRect(10, 10, 201, 21))
        self.label_40.setObjectName("label_40")
        self.textEdit_5 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_5.setGeometry(QtCore.QRect(130, 30, 131, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.Input_img_4 = QtWidgets.QLabel(self.tab_5)
        self.Input_img_4.setGeometry(QtCore.QRect(230, 20, 521, 271))
        self.Input_img_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_img_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Input_img_4.setObjectName("Input_img_4")
        self.Hough_load_5 = QtWidgets.QPushButton(self.tab_5)
        self.Hough_load_5.setGeometry(QtCore.QRect(30, 20, 121, 81))
        self.Hough_load_5.setObjectName("Hough_load_5")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(30, 160, 71, 21))
        self.label_33.setObjectName("label_33")
        self.clear = QtWidgets.QPushButton(self.tab_5)
        self.clear.setGeometry(QtCore.QRect(30, 260, 101, 31))
        self.clear.setObjectName("clear")
        self.apply = QtWidgets.QPushButton(self.tab_5)
        self.apply.setGeometry(QtCore.QRect(30, 310, 101, 31))
        self.apply.setObjectName("apply")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(220, 310, 231, 151))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(10, 0, 91, 21))
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(60, 30, 61, 21))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setGeometry(QtCore.QRect(60, 70, 61, 21))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setGeometry(QtCore.QRect(60, 110, 61, 21))
        self.label_38.setObjectName("label_38")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setGeometry(QtCore.QRect(130, 30, 61, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 70, 61, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_3.setGeometry(QtCore.QRect(130, 110, 61, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Template_matching_inputA = QtWidgets.QLabel(self.tab)
        self.Template_matching_inputA.setGeometry(QtCore.QRect(200, 0, 231, 231))
        self.Template_matching_inputA.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_matching_inputA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_matching_inputA.setObjectName("Template_matching_inputA")
        self.Matchingspace = QtWidgets.QLabel(self.tab)
        self.Matchingspace.setGeometry(QtCore.QRect(460, 0, 231, 231))
        self.Matchingspace.setFrameShape(QtWidgets.QFrame.Box)
        self.Matchingspace.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Matchingspace.setObjectName("Matchingspace")
        self.Template_matching_inputB = QtWidgets.QLabel(self.tab)
        self.Template_matching_inputB.setGeometry(QtCore.QRect(200, 240, 231, 231))
        self.Template_matching_inputB.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_matching_inputB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_matching_inputB.setObjectName("Template_matching_inputB")
        self.Detected_patterns = QtWidgets.QLabel(self.tab)
        self.Detected_patterns.setGeometry(QtCore.QRect(460, 240, 231, 231))
        self.Detected_patterns.setFrameShape(QtWidgets.QFrame.Box)
        self.Detected_patterns.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Detected_patterns.setObjectName("Detected_patterns")
        self.label_53 = QtWidgets.QLabel(self.tab)
        self.label_53.setGeometry(QtCore.QRect(50, 150, 71, 21))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab)
        self.label_54.setGeometry(QtCore.QRect(50, 120, 71, 21))
        self.label_54.setObjectName("label_54")
        self.Load_imageA = QtWidgets.QPushButton(self.tab)
        self.Load_imageA.setGeometry(QtCore.QRect(40, 10, 121, 81))
        self.Load_imageA.setObjectName("Load_imageA")
        self.label_55 = QtWidgets.QLabel(self.tab)
        self.label_55.setGeometry(QtCore.QRect(50, 390, 71, 21))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab)
        self.label_56.setGeometry(QtCore.QRect(50, 360, 71, 21))
        self.label_56.setObjectName("label_56")
        self.Load_imageB = QtWidgets.QPushButton(self.tab)
        self.Load_imageB.setGeometry(QtCore.QRect(40, 250, 121, 81))
        self.Load_imageB.setObjectName("Load_imageB")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(710, 20, 221, 201))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label_16.setObjectName("label_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 40, 171, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_match = QtWidgets.QPushButton(self.tab)
        self.pushButton_match.setGeometry(QtCore.QRect(750, 240, 121, 61))
        self.pushButton_match.setObjectName("pushButton_match")
        self.label_58 = QtWidgets.QLabel(self.tab)
        self.label_58.setGeometry(QtCore.QRect(750, 330, 281, 41))
        self.label_58.setObjectName("label_58")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_59 = QtWidgets.QLabel(self.tab_2)
        self.label_59.setGeometry(QtCore.QRect(30, 370, 71, 21))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_2)
        self.label_60.setGeometry(QtCore.QRect(30, 400, 71, 21))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_2)
        self.label_61.setGeometry(QtCore.QRect(30, 160, 71, 21))
        self.label_61.setObjectName("label_61")
        self.Load_imageA_2 = QtWidgets.QPushButton(self.tab_2)
        self.Load_imageA_2.setGeometry(QtCore.QRect(20, 20, 121, 81))
        self.Load_imageA_2.setObjectName("Load_imageA_2")
        self.Load_imageB_2 = QtWidgets.QPushButton(self.tab_2)
        self.Load_imageB_2.setGeometry(QtCore.QRect(20, 260, 121, 81))
        self.Load_imageB_2.setObjectName("Load_imageB_2")
        self.label_62 = QtWidgets.QLabel(self.tab_2)
        self.label_62.setGeometry(QtCore.QRect(30, 130, 71, 21))
        self.label_62.setObjectName("label_62")
        self.Template_matching_inputA_3 = QtWidgets.QLabel(self.tab_2)
        self.Template_matching_inputA_3.setGeometry(QtCore.QRect(180, 10, 231, 201))
        self.Template_matching_inputA_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_matching_inputA_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_matching_inputA_3.setObjectName("Template_matching_inputA_3")
        self.Template_matching_inputB2 = QtWidgets.QLabel(self.tab_2)
        self.Template_matching_inputB2.setGeometry(QtCore.QRect(180, 230, 231, 231))
        self.Template_matching_inputB2.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_matching_inputB2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_matching_inputB2.setObjectName("Template_matching_inputB2")
        self.SIFT_output = QtWidgets.QLabel(self.tab_2)
        self.SIFT_output.setGeometry(QtCore.QRect(420, 40, 431, 371))
        self.SIFT_output.setFrameShape(QtWidgets.QFrame.Box)
        self.SIFT_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SIFT_output.setObjectName("SIFT_output")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_24.setGeometry(QtCore.QRect(910, 50, 171, 201))
        self.groupBox_24.setTitle("")
        self.groupBox_24.setObjectName("groupBox_24")
        self.label_8 = QtWidgets.QLabel(self.groupBox_24)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit.setGeometry(QtCore.QRect(10, 80, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 130, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_24)
        self.label_9.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_135 = QtWidgets.QLabel(self.groupBox_24)
        self.label_135.setGeometry(QtCore.QRect(10, 0, 151, 31))
        self.label_135.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_135.setObjectName("label_135")
        self.pushButton_match_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_match_4.setGeometry(QtCore.QRect(930, 270, 121, 61))
        self.pushButton_match_4.setObjectName("pushButton_match_4")
        self.label_136 = QtWidgets.QLabel(self.tab_2)
        self.label_136.setGeometry(QtCore.QRect(860, 370, 351, 71))
        self.label_136.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_136.setObjectName("label_136")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1340, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_filters_input.setText(_translate("MainWindow", "Input image"))
        self.label_filters_output.setText(_translate("MainWindow", "Output image"))
        self.pushButton_filters_load.setText(_translate("MainWindow", "Load Image"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Size:"))
        self.label_3.setText(_translate("MainWindow", "Select Filter"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Gaussian Noise"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Salt&Pepper Noise"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Uniform Noise"))
        self.label_4.setText(_translate("MainWindow", "Select Noise"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Robert detection"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Canny detection"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Sobel detection"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Prewitt detection"))
        self.label_5.setText(_translate("MainWindow", "Edge detection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.label_histograms_houtput.setText(_translate("MainWindow", "Output Histogram"))
        self.label_histograms_input.setText(_translate("MainWindow", "Input image"))
        self.label_histograms_output.setText(_translate("MainWindow", "Output image"))
        self.label_10.setText(_translate("MainWindow", "Size:"))
        self.label_11.setText(_translate("MainWindow", "Name:"))
        self.label_histograms_hinput.setText(_translate("MainWindow", "Input Histogram"))
        self.label_histograms_hinput_3.setText(_translate("MainWindow", "Input image in RGB"))
        self.label_6.setText(_translate("MainWindow", "GrayScale Histogram & equalization"))
        self.label_histograms_hinput_4.setText(_translate("MainWindow", "Coloured  Histogram"))
        self.pushButton_histograms_load.setText(_translate("MainWindow", "Load image"))
        self.label_7.setText(_translate("MainWindow", "Coloured Histogram "))
        self.coloredhistogram.setText(_translate("MainWindow", "Coloured Histogram"))
        self.equalization.setText(_translate("MainWindow", "Equalization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_histograms), _translate("MainWindow", "Histograms"))
        self.label_histograms_input_2.setText(_translate("MainWindow", "Input image A"))
        self.label_histograms_hinput_2.setText(_translate("MainWindow", "Input image B"))
        self.label_histograms_output_2.setText(_translate("MainWindow", "Output image"))
        self.label_12.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_2.setText(_translate("MainWindow", "Load image A"))
        self.label_13.setText(_translate("MainWindow", "Size:"))
        self.label_14.setText(_translate("MainWindow", "Size:"))
        self.label_15.setText(_translate("MainWindow", "Name:"))
        self.pushButton_histograms_load_3.setText(_translate("MainWindow", "Load image B"))
        self.pushButton_histograms_load_4.setText(_translate("MainWindow", "Make Hybrid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hybrid), _translate("MainWindow", "Hybrid"))
        self.output_img.setText(_translate("MainWindow", "Output image"))
        self.Hough_load.setText(_translate("MainWindow", "Load image "))
        self.label_27.setText(_translate("MainWindow", "Name:"))
        self.label_28.setText(_translate("MainWindow", "Size:"))
        self.label_29.setText(_translate("MainWindow", "Select Shapes"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Circles"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Lines"))
        self.Hough_load_2.setText(_translate("MainWindow", "Apply"))
        self.Input_img_2.setText(_translate("MainWindow", "Input image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Hough"))
        self.Input_img_3.setText(_translate("MainWindow", "Input image"))
        self.output_img_2.setText(_translate("MainWindow", "Output image"))
        self.Hough_load_3.setText(_translate("MainWindow", "Load image "))
        self.label_30.setText(_translate("MainWindow", "Name:"))
        self.label_31.setText(_translate("MainWindow", "Size:"))
        self.Hough_load_4.setText(_translate("MainWindow", "Apply"))
        self.label_39.setText(_translate("MainWindow", "Edge detector turnable parameter"))
        self.label_40.setText(_translate("MainWindow", "Operator turnable parameter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Harris"))
        self.Input_img_4.setText(_translate("MainWindow", "Input image"))
        self.Hough_load_5.setText(_translate("MainWindow", "Load image "))
        self.label_32.setText(_translate("MainWindow", "Name:"))
        self.label_33.setText(_translate("MainWindow", "Size:"))
        self.clear.setText(_translate("MainWindow", "Clear Anchors"))
        self.apply.setText(_translate("MainWindow", "Apply"))
        self.label_34.setText(_translate("MainWindow", "Contour setting"))
        self.label_36.setText(_translate("MainWindow", "Alpha"))
        self.label_37.setText(_translate("MainWindow", "Beta"))
        self.label_38.setText(_translate("MainWindow", "Gamma"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Active contour"))
        self.Template_matching_inputA.setText(_translate("MainWindow", "Input image A"))
        self.Matchingspace.setText(_translate("MainWindow", "Matching space"))
        self.Template_matching_inputB.setText(_translate("MainWindow", "Input image B"))
        self.Detected_patterns.setText(_translate("MainWindow", "Detected patterns"))
        self.label_53.setText(_translate("MainWindow", "Size:"))
        self.label_54.setText(_translate("MainWindow", "Name:"))
        self.Load_imageA.setText(_translate("MainWindow", "Load Image A"))
        self.label_55.setText(_translate("MainWindow", "Size:"))
        self.label_56.setText(_translate("MainWindow", "Name:"))
        self.Load_imageB.setText(_translate("MainWindow", "Load Image B"))
        self.label_16.setText(_translate("MainWindow", "Choose the matching method"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Correlation"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Zero-mean correlation"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Sum of squared differences (SSD)"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Normalized cross correlations"))
        self.pushButton_match.setText(_translate("MainWindow", "Match"))
        self.label_58.setText(_translate("MainWindow", "Time elapsed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Template matching"))
        self.label_59.setText(_translate("MainWindow", "Name:"))
        self.label_60.setText(_translate("MainWindow", "Size:"))
        self.label_61.setText(_translate("MainWindow", "Size:"))
        self.Load_imageA_2.setText(_translate("MainWindow", "Load Image A"))
        self.Load_imageB_2.setText(_translate("MainWindow", "Load Image B"))
        self.label_62.setText(_translate("MainWindow", "Name:"))
        self.Template_matching_inputA_3.setText(_translate("MainWindow", "Input image A"))
        self.Template_matching_inputB2.setText(_translate("MainWindow", "Input image B"))
        self.SIFT_output.setText(_translate("MainWindow", "Output image"))
        self.label_8.setText(_translate("MainWindow", "No of octaves"))
        self.lineEdit.setText(_translate("MainWindow", "4"))
        self.lineEdit_2.setText(_translate("MainWindow", "1.6"))
        self.label_9.setText(_translate("MainWindow", "Sigma"))
        self.label_135.setText(_translate("MainWindow", "Default Turnable  parameters"))
        self.pushButton_match_4.setText(_translate("MainWindow", "Match"))
        self.label_136.setText(_translate("MainWindow", "Time elapsed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "SIFT"))

